# Generated by Django 4.2.3 on 2024-01-26 18:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('invested_score', models.IntegerField(default=0)),
                ('owner_starts', models.BooleanField(default=False)),
                ('daylater', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2024, 1, 26, 18, 18, 40, 345185, tzinfo=datetime.timezone.utc))),
                ('invested_score', models.IntegerField(default=0)),
                ('owner_starts', models.BooleanField(default=True)),
                ('daylater', models.BooleanField(default=False)),
                ('scoreback', models.IntegerField(default=-1)),
                ('scorebackinfo', models.TextField(default='')),
                ('scorebackreal', models.TextField(default='')),
                ('aboutstart', models.BooleanField(default=False)),
                ('reached2000', models.BooleanField(default=False)),
                ('ownsrob', models.BooleanField(default=False)),
                ('Textbox', models.TextField(default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
