# Generated by Django 4.1.2 on 2023-04-27 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='credit',
            name='daylater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='invested_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credit',
            name='owner_starts',
            field=models.BooleanField(default=False),
        ),
    ]
