# Generated by Django 4.2.3 on 2024-01-26 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 26, 18, 42, 19, 610737, tzinfo=datetime.timezone.utc)),
        ),
    ]
