# Generated by Django 4.1.2 on 2023-05-20 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_credit_date_posted_alter_credit_owner_starts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 19, 2, 43, 466408, tzinfo=datetime.timezone.utc)),
        ),
    ]
