# Generated by Django 4.1.2 on 2023-05-20 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 19, 4, 19, 524848, tzinfo=datetime.timezone.utc)),
        ),
    ]
