# Generated by Django 4.2.3 on 2024-01-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_credit_textbox_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='matchready',
            field=models.BooleanField(default=False),
        ),
    ]
