# Generated by Django 4.1.2 on 2023-05-22 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 18, 1, 15, 67790, tzinfo=datetime.timezone.utc)),
        ),
    ]
