# Generated by Django 4.2.3 on 2024-01-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_credit_matchready'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='Matchfield',
            field=models.TextField(default=''),
        ),
    ]
