# Generated by Django 4.2.3 on 2024-02-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_credit_matchfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='Matchfield',
        ),
    ]
