# Generated by Django 4.2.3 on 2024-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_credit_matchfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='splitpass',
            field=models.BooleanField(default=False),
        ),
    ]
