# Generated by Django 4.1.2 on 2023-06-06 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 17, 17, 59, 616746, tzinfo=datetime.timezone.utc)),
        ),
    ]
