# Generated by Django 4.1.2 on 2023-06-06 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_credit_date_posted_alter_credit_scoreback'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='scorebackinfo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 18, 36, 28, 699154, tzinfo=datetime.timezone.utc)),
        ),
    ]
