# Generated by Django 4.1.2 on 2023-06-06 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_credit_scorebackinfo_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 18, 41, 33, 149406, tzinfo=datetime.timezone.utc)),
        ),
    ]
