# Generated by Django 4.2.3 on 2023-07-15 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_credit_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 15, 18, 44, 33, 141344, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
