# Generated by Django 4.2.3 on 2023-07-19 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='aboutstart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 18, 9, 2, 479064, tzinfo=datetime.timezone.utc)),
        ),
    ]
