# Generated by Django 4.2.3 on 2023-07-22 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 22, 16, 53, 21, 713655, tzinfo=datetime.timezone.utc)),
        ),
    ]
