# Generated by Django 4.2.3 on 2023-07-27 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_credit_reached2000_alter_credit_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 17, 34, 41, 597366, tzinfo=datetime.timezone.utc)),
        ),
    ]
