# Generated by Django 4.2.3 on 2023-07-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_credit_aboutstart_alter_credit_date_posted"),
        ("users", "0023_alter_credit_date_posted"),
    ]

    operations = []
