
# Generated by Django 4.2.3 on 2023-07-28 17:33

# Generated by Django 4.2.3 on 2023-07-27 17:38


import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("users", "0023_alter_credit_date_posted_alter_credit_scoreback"),

        ('users', '0023_alter_credit_date_posted'),

    ]

    operations = [
        migrations.AlterField(

            model_name="credit",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 28, 17, 33, 34, 773891, tzinfo=datetime.timezone.utc
                )
            ),

            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 17, 38, 50, 738330, tzinfo=datetime.timezone.utc)),

        ),
    ]
