# Generated by Django 4.2.3 on 2023-07-28 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_merge_20230728_1853"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 28, 18, 53, 51, 609575, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
