# Generated by Django 4.1.2 on 2023-05-29 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_credit_scoreback_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 17, 53, 21, 880924, tzinfo=datetime.timezone.utc)),
        ),
    ]
