# Generated by Django 4.1.2 on 2023-06-06 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_credit_date_posted_alter_credit_scoreback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 18, 24, 3, 858557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='credit',
            name='scoreback',
            field=models.IntegerField(default=0),
        ),
    ]
