# Generated by Django 4.1.2 on 2023-06-10 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_credit_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='scorebackreal',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='credit',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 17, 59, 16, 871567, tzinfo=datetime.timezone.utc)),
        ),
    ]
