# Generated by Django 4.2.3 on 2023-09-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troll', '0005_alter_chat_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='posted',
            new_name='chatted',
        ),
    ]
