# Generated by Django 4.2.3 on 2023-10-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troll', '0007_remove_chat_chatted_chat_should_refresh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='should_refresh',
        ),
    ]
