# Generated by Django 4.2.3 on 2024-01-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('troll', '0008_remove_chat_should_refresh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
