# Generated by Django 4.2.3 on 2024-02-27 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('troll', '0010_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fight',
            name='Matchfield',
            field=models.TextField(default=''),
        ),
    ]
