# Generated by Django 4.2.3 on 2024-03-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troll', '0014_fight_messageback'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='selectedbool',
            field=models.BooleanField(default=False),
        ),
    ]
