# Generated by Django 4.2.3 on 2024-03-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('troll', '0017_fight_secondredir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='secondredir',
            field=models.TextField(default=''),
        ),
    ]
